// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tanulok.Data;

#nullable disable

namespace Tanulok.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220517163837_Osztaly")]
    partial class Osztaly
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tanulok.Model.Diak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiakNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Osztaly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TanarNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Diakok");
                });
#pragma warning restore 612, 618
        }
    }
}
